### ISSUE TITLE
Make the dataset available via Hugging Face Hub 

### ISSUE THREAD

**Issue by davanstrien** [CyberAgentAILab/camera#3]
Thanks for creating this dataset. It would be great to also make this dataset available via the Hugging Face Hub (https://huggingface.co/datasets). Having looked at the dataset's structure, it should be pretty easy to make it available on the Hub, but feel free to ping me if you are interested and want any support getting it uploaded.

**Comment by shunk031** [comment]
Hi, I have already created the dataset as follows: https://huggingface.co/datasets/shunk031/CAMERA

I would be happy to help you.

**Comment by davanstrien** [comment]
Awesome! That's great to see. I made a small PR to the README to add the link :)
